# Generated by Django 5.2 on 2025-11-19 11:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('fabricante', models.CharField(max_length=50)),
                ('quantidade_estoque', models.IntegerField(default=0)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_minimo', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('esgotado', 'Esgotado'), ('descontinuado', 'Descontinuado')], default='disponivel', max_length=15)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('mecanico', 'Mecânico'), ('gerente', 'Gerente')], default='cliente', max_length=20)),
                ('cpf', models.CharField(help_text='CPF no formato 000.000.000-00', max_length=14, unique=True)),
                ('telefone', models.CharField(help_text='Telefone com DDD', max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateField()),
                ('descricao_problema', models.TextField()),
                ('valor_mao_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('expirado', 'Expirado')], default='pendente', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('mecanico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_previsao', models.DateField()),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_andamento', 'Em Andamento'), ('aguardando_pecas', 'Aguardando Peças'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('km_entrada', models.IntegerField(help_text='Quilometragem na entrada')),
                ('orcamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servico', to='backend.orcamento')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa do veículo no formato ABC-1234 ou ABC1D23', max_length=10, unique=True)),
                ('marca', models.CharField(help_text='Marca do veículo (ex: Toyota, Honda, Volkswagen)', max_length=50)),
                ('modelo', models.CharField(help_text='Modelo do veículo (ex: Corolla, Civic, Golf)', max_length=50)),
                ('ano', models.IntegerField(help_text='Ano de fabricação do veículo')),
                ('cor', models.CharField(help_text='Cor do veículo', max_length=30)),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o veículo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(help_text='Proprietário do veículo', on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['marca', 'modelo', 'ano'],
            },
        ),
        migrations.AddField(
            model_name='orcamento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='backend.veiculo'),
        ),
        migrations.CreateModel(
            name='ItemPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_unitario_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pecas', to='backend.ordemservico')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_utilizados', to='backend.peca')),
            ],
            options={
                'verbose_name': 'Item Peça',
                'verbose_name_plural': 'Itens Peças',
                'ordering': ['peca__nome'],
                'unique_together': {('ordem_servico', 'peca')},
            },
        ),
    ]
