# Generated by Django 5.2 on 2025-11-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempeca',
            name='estoque_reduzido',
            field=models.BooleanField(default=False, help_text='Indica se o estoque já foi reduzido'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='desconto_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
