# Generated by Django 5.2 on 2025-11-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_itempeca_estoque_reduzido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
